name: Build and Deploy Angular App to ACR

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name (main, master, etc.)
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Adjust to your Angular app's Node version
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Angular app
      run: npm run build --prod
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Docker Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and Push to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/gmpocfrontend:latest,${{ secrets.ACR_LOGIN_SERVER }}/gmpocfrontend:${{ github.sha }}
        file: Dockerfile
        context: .
