BEGIN
  FOR t IN (
    SELECT table_name
    FROM (
      SELECT 'TNOTICEMST' AS table_name FROM DUAL UNION ALL
      SELECT 'IFSUMIPAM_PART' FROM DUAL UNION ALL
      SELECT 'IFSUMIPAM_PART_D' FROM DUAL UNION ALL
      SELECT 'IFSUMIPAM_PART_D_EKAN' FROM DUAL UNION ALL
      SELECT 'IFKDREQ_D_GS' FROM DUAL UNION ALL
      SELECT 'IFKDREQ_D_BP' FROM DUAL UNION ALL
      SELECT 'IFKDREQ_D_CW' FROM DUAL UNION ALL
      SELECT 'IFPART12_A_GS' FROM DUAL UNION ALL
      SELECT 'IFPART12_A_CW' FROM DUAL UNION ALL
      SELECT 'IFPART12_A_BP' FROM DUAL UNION ALL
      SELECT 'IFPART12_A_WEEK' FROM DUAL UNION ALL
      SELECT 'IFASN01H' FROM DUAL UNION ALL
      SELECT 'CONV_MGO_DELFOR' FROM DUAL UNION ALL
      SELECT 'IFMS3YINPT_WEEK' FROM DUAL
    )
  ) LOOP
    FOR c IN (
      SELECT column_name, data_length
      FROM all_tab_columns
      WHERE table_name = t.table_name
        AND owner = 'SYSTEM'
        AND data_type = 'VARCHAR2'
        AND data_length < 60
    ) LOOP
      EXECUTE IMMEDIATE 'ALTER TABLE SYSTEM.' || t.table_name || 
                        ' MODIFY ' || c.column_name || ' VARCHAR2(60)';
    END LOOP;
  END LOOP;
END;
/



BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.TNOTICEMST CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFSUMIPAM_PART CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFSUMIPAM_PART_D CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFSUMIPAM_PART_D_EKAN CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFKDREQ_D_GS CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFKDREQ_D_BP CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFKDREQ_D_CW CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFPART12_A_GS CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFPART12_A_CW CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFPART12_A_BP CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFPART12_A_WEEK CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFASN01H CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.CONV_MGO_DELFOR CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE SYSTEM.IFMS3YINPT_WEEK CASCADE CONSTRAINTS';
END;
/
