name: SonarQube-Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, reopened]

jobs:
  SonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up Java 20
        uses: actions/setup-java@v3  # Updated to v3
        with:
          java-version: '20'
          distribution: 'temurin'  # Ensure the distribution supports Java 20

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          
          # Add logback dependencies to sonar-scanner's classpath
          mkdir -p /opt/sonar-scanner/lib/ext
          
          # Download the missing logback dependencies
          wget -P /opt/sonar-scanner/lib/ext https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.4.11/logback-classic-1.4.11.jar
          wget -P /opt/sonar-scanner/lib/ext https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.4.11/logback-core-1.4.11.jar
          
          echo "SONAR_SCANNER_HOME=/opt/sonar-scanner" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Verify Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Create sonar-project.properties
        run: |
          cat > sonar-project.properties << EOF
          # Required properties
          sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          sonar.projectName=${{ github.repository_owner }}/${{ github.event.repository.name }}
          sonar.projectVersion=1.0
          
          # Source directories
          sonar.sources=src/main
          sonar.java.binaries=target/classes
          sonar.java.source=20
          
          # Tests
          sonar.tests=src/test
          sonar.java.test.binaries=target/test-classes
          
          # Encoding
          sonar.sourceEncoding=UTF-8
          
          # Coverage & Reports
          sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          sonar.junit.reportPaths=target/surefire-reports
          EOF
          
          cat sonar-project.properties
      
      - name: Run SonarQube Scan
        run: |
          export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
          sonar-scanner -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: "-Xmx2048m"  # Increased memory
