SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB
FROM DBA_SEGMENTS
WHERE TABLESPACE_NAME = 'USERS' -- or your tablespace
ORDER BY SIZE_MB DESC;



ALTER TABLE your_table_name ENABLE ROW MOVEMENT;
ALTER TABLE your_table_name SHRINK SPACE;


SELECT FILE_NAME, BYTES/1024/1024 AS SIZE_MB
FROM DBA_DATA_FILES
WHERE TABLESPACE_NAME = 'USERS'; -- or your actual tablespace




ALTER DATABASE DATAFILE '/path/to/your/file.dbf' RESIZE 500M;

DROP TABLESPACE your_tablespace INCLUDING CONTENTS AND DATAFILES;
